version: "3.7"

networks:
  dev:

services:
  autocomplete:
    image: autocomplete:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - AUTOCOMPLETE_API_RedisSettings__Hosts__0=redisearch:6379
    networks:
      - dev
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  redisearch:
    image: redislabs/redisearch:latest
    ports:
      - 6381:6379
    networks:
      - dev